pandas_profiling:
  _run: false
  sample_fraction: 1.0
  params:
    samples:
      head: 5
      tail: 5
    interactions: null

feat_selection_k_best:
  _run: true
  k: 3

feat_selection_metrics:
  _run: true


data_split:
  _run: true
  val_size: 0.15
  test_size: 0.15
  stratify: True

category_encoder:
  _run: true

general:
  columns_to_keep: null
  columns_to_drop: null
  # The columns listed here are converted to categorical
  # features using sklearn LabelEncoder. Set it to null
  # in case the features don't need to be converted
  columns_categorical:
    - buying
    - maint
    - doors
    - persons
    - lug_boot
    - safety
  column_target: class
  prng_seed: 12345
