feature_analysis:
  pandas_profile:
    sample_fraction: 1.0
    params:
      samples:
        head: 5
        tail: 5
      interactions: null

feature_selection:
data_split:
  # dev_size
  dev_fraction: 0.2
  stratify: True

general:
  columns_to_keep: null
  columns_to_drop: null
  column_target: survived
  prng_seed: 12345