feature_analysis:
  pandas_profile:
    sample_fraction: 1.0
    params:
      samples:
        head: 5
        tail: 5
      interactions: null

feat_selection_k_best:
  k: 3

data_split:
  #
  val_size: 0.15
  test_size: 0.15
  stratify: True

general:
  columns_to_keep: null
  columns_to_drop: null
  column_target: variety
  prng_seed: 12345
