feature_analysis:
  pandas_profile:
    sample_fraction: 1.0
    params:
      samples:
        head: 5
        tail: 5
      interactions: null

# feature_selection:

columns_to_keep: null
columns_to_drop: null
columns_target: target